apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    kubernetes.io/app: web
  annotations:
    test: test annotation for you Guys! 
spec:
  containers:
  - name: web
    image: nginx:1.14.2

