apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    os: ubuntu
  name: second-pod
spec:
  containers:
  - image: ubuntu
    name: second-pod
    command: ["sh", "-c", "tail -F /tmp/test"]
    resources: {}
  dnsPolicy: ClusterFirst
status: {}
