apiVersion: v1
data:
  index.html: |+
    <!DOCTYPE html>
    <html lang="pl">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Pozdrowienia LFS458</title>
        <style>
            body {
                margin: 0;
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                background: linear-gradient(to right, #83a4d4, #b6fbff);
                display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: center;
                height: 100vh;
                text-align: center;
                color: #333;
            }
            h1 {
                font-size: 2.5em;
                margin-bottom: 30px;
                color: #2c3e50;
                text-shadow: 1px 1px 4px rgba(0,0,0,0.2);
            }
            img {
                max-width: 90%;
                height: auto;
                border: 5px solid #fff;
                box-shadow: 0 4px 15px rgba(0,0,0,0.3);
                border-radius: 10px;
            }
        </style>
    </head>
    <body>
        <h1>{{ .Values.website.content }}</h1>
        <img src="https://via.placeholder.com/600x400.png?text=Zdjęcie+ze+szkolenia" alt="Zdjęcie szkoleniowe">
    </body>
    </html>

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: web-index
