apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
spec:
  nodename: {{ .Values.nodeName }} 
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes: 
      - name: config-volume
        configMap:
          name: web-index
      containers:
      - image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: nginx
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
