apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      {{- if .Values.service.nodePort.enabled }}
      nodeName: {{ .Values.service.nodePort.port }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    app: nginx
