# Default values for myhelmchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  name: nginx
  tag: 1.19.2
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort:
    enabled: true
    port: 30080

nodeName: worker01

website:
  content: "Pozdrowienia dla wszystkich ze szkolenia LFS458!"
