apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-mariadb-pv
spec:
  storageClassName: ""
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
