apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  volumes:
  - name: www-data
    emptyDir: {}
  initContainers:
  - name: prepare
    image: alpine:3.2 
    command: ['sh', '-c', 'apk update; apk add git; git clone -b develop https://github.com/mariano-italiano/lfs458_Jun.git /data; echo "init contained done, git cloned and content saved"']
    volumeMounts:
    - name: www-data
      mountPath: /data
  containers:
  - name: web
    image: nginx
    volumeMounts:
    - name: www-data
      mountPath: /usr/share/nginx/html
