apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: web
        image: nginx
